// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCl3sqPZ_EfT7tVlOKwE8b2cfvqYU8QqRY',
    appId: '1:973350463427:web:a37880ba8341e8ce097f76',
    messagingSenderId: '973350463427',
    projectId: 'sugargo-bd9c2',
    authDomain: 'sugargo-bd9c2.firebaseapp.com',
    storageBucket: 'sugargo-bd9c2.firebasestorage.app',
    measurementId: 'G-WYH3BB2YHT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7MoIYUlgeEKkRhKzTJDqVVEMqLshAf4s',
    appId: '1:973350463427:android:0c7529373895e1bd097f76',
    messagingSenderId: '973350463427',
    projectId: 'sugargo-bd9c2',
    storageBucket: 'sugargo-bd9c2.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCl3sqPZ_EfT7tVlOKwE8b2cfvqYU8QqRY',
    appId: '1:973350463427:web:15f87fc4c6f35ff5097f76',
    messagingSenderId: '973350463427',
    projectId: 'sugargo-bd9c2',
    authDomain: 'sugargo-bd9c2.firebaseapp.com',
    storageBucket: 'sugargo-bd9c2.firebasestorage.app',
    measurementId: 'G-WLESNQ0D1P',
  );

}